version: 2.1

workflows:
  main:
    jobs:
      - build
      - publish-snap:
          requires:
            - build
          filters:
            branches:
              only: master
          context: main

jobs:
  build:
    docker:
      - image: cibuilds/snapcraft:core20
    steps:
      - checkout
      - run:
          name: "Build Snap"
          command: snapcraft
      - persist_to_workspace:
          root: .
          paths:
            - "*.snap"

  publish-snap:
    docker:
      - image: cibuilds/snapcraft:core20
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Copy artifact to folder
          command: |
            mkdir artifacts
            cp *.snap artifacts
      - store_artifacts:
          path: artifacts
      - run:
          name: "Publish to Store"
          command: |
            mkdir .snapcraft
            echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > .snapcraft/snapcraft.cfg
            snapcraft push --release=stable *.snap
