name: scc
title: "scc"
version: v3.7.0
summary: "scc is a very fast & accurate code counter counting lines of code by language."
description: |
  A tool similar to cloc, sloccount and tokei. For counting physical the lines of code, blank lines, comment lines, and physical lines of source code in many programming languages.

  Goal is to be the fastest code counter possible, but also perform COCOMO calculation like sloccount and to estimate code complexity similar to cyclomatic complexity calculators.

  scc is made by Ben Boyter. This snap is packaged by Ricardo N Feliciano (FelicianoTech) using the `scc` source code available by Ben on GitHub.
contact: https://github.com/FelicianoTech/snap-scc/issues
source-code: https://github.com/FelicianoTech/snap-scc
issues:
  - https://github.com/FelicianoTech/snap-scc/issues
  - https://github.com/boyter/scc/issues
website: https://github.com/FelicianoTech/snap-scc
grade: stable
confinement: strict
icon: icon.png
base: core24

platforms:
  amd64:
  arm64:
  armhf:

apps:
  scc:
    command: bin/scc
    plugs:
      - home

parts:
  go:
    plugin: go
    build-snaps:
      - go
    source: https://github.com/boyter/scc
    source-type: git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-depth: 1
